[
	{"title":"The Shawshank Redemption",
		"featured": true,
		"year":"1994","urlPoster":
		"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p480747492.jpg",
		"IMDbrating":"9.2",
		"description": "IMDb: Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
		"urlTrailer":"https://www.youtube.com/embed/6hB3S9bIaco?rel=0",
		"comments":[]
	},
	{"title":"The Godfather",
		"year":"1972",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2190556185.jpg",
		"IMDbrating":"9.2",
		"description": "IMDb: The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
		"urlTrailer":"https://www.youtube.com/embed/sY1S34973zA?rel=0",
		"comments":[]
	},
	{"title":"The Godfather: Part II",
		"year":"1974",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2194138787.jpg",
		"IMDbrating":"9.0",
		"description": "IMDb: The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
		"urlTrailer":"https://www.youtube.com/embed/9O1Iy9od7-A?rel=0",
		"comments":[]
	},
	{"title":"The Dark Knight",
		"featured": true,
		"year":"2008",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p462657443.jpg",
		"IMDbrating":"9.0",
		"description": "IMDb: When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
		"urlTrailer":"https://www.youtube.com/embed/EXeTwQWrcwY?rel=0",
		"comments":[]
	},
	{"title":"12 Angry Men",
		"year":"1957",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2173577632.jpg",
		"IMDbrating":"8.9",
		"description": "IMDb: A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
		"urlTrailer":"https://www.youtube.com/embed/A7CBKT0PWFA?rel=0",
		"comments":[]
	},
	{"title":"Schindler's List",
		"featured": true,
		"year":"1993",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p492406163.jpg",
		"IMDbrating":"8.9",
		"description": "IMDb: In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.",
		"urlTrailer":"https://www.youtube.com/embed/JdRGC-w9syA?rel=0",
		"comments":[]
	},
	{"title":"The Lord of the Rings: The Return of the King",
		"year":"2003",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910825503.jpg",
		"IMDbrating":"8.9",
		"description": "IMDb: Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
		"urlTrailer":"https://www.youtube.com/embed/r5X-hFf6Bwo?rel=0",
		"comments":[]
	},
	{"title":"Pulp Fiction",
		"year":"1994",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910902213.jpg",
		"IMDbrating":"8.9",
		"description": "IMDb: The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
		"urlTrailer":"https://www.youtube.com/embed/s7EdQ4FqbhY?rel=0",
		"comments":[]
	},
	{"title":"The Good, the Bad and the Ugly","year":"1966",
		"urlPoster":"https://img1.doubanio.com/view/photo/l/public/p920850879.webp",
		"IMDbrating":"8.8",
		"description": "IMDb: A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
		"urlTrailer":"https://www.youtube.com/embed/WCN5JJY_wiA?rel=0",
		"comments":[]
	},
	{"title":"Fight Club",
		"year":"1999",
		"urlPoster":"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910926158.jpg",
		"IMDbrating":"8.8",
		"description": "IMDb: An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soapmaker, forming an underground fight club that evolves into something much, much more.",
		"urlTrailer":"https://www.youtube.com/embed/SUXWAEX2jlg?rel=0",
		"comments":[]
	}
]

